#define SLEEP_TIME 200000
#define PORT_MAG "/dev/ttyUSB0"
#define PORT_TEMP "/dev/ttyUSB1"
#define WAKE_UP_BAUD 300
#define BAUD_MAG 9600
#define BAUD_TEMP 4800
#define MAG_DATA_FILE "/home/daq/ReadRS232/Mag&Temp/bin/magData.txt" 
#define TEMP_DATA_FILE "/home/daq/ReadRS232/Mag&Temp/bin/tempData.txt" 
#define WATCHDOG_DATA "/home/daq/Watchdog/bin/magTemp.txt" 
