#!/bin/bash

DAQ=$1

if [ $# != 1 ]
then
    echo "Please Power reboot one module at a time"
    exit
fi


PingIP()
{
    echo "Checking if IP Power strip is connected ..."
    IP=192.168.0.$1
    ping -c 1 $IP > /dev/null
    STATUS=$?
    if [ $STATUS -eq 0 ]
    then
	echo "IP Power strip is Connected."
    else
	echo "IP Power strip is NOT Connected."
	exit
    fi
}

ResetPower()
{
    if [ $DAQ == 21 ] || [ $DAQ == 22 ] || [ $DAQ == 23 ] || [ $DAQ == 24 ]
    then
	case "$DAQ" in
	    "21") ARG1=1110
		;;
	    "22") ARG1=1101
		;;
	    "23") ARG1=1011
		;;
	    "24") ARG1=0111
		;;
	esac
	ARG2=1111
	PingIP 100
	if [ -f /home/daq/Diagnosis/power_reset_clean.sh ] 
	then
	    echo "Resetting the power of DAQ $DAQ ..."
	    echo "It might take about 20 sec. Please wait ... ..."
	    /home/daq/Diagnosis/power_reset_clean.sh $ARG1 $ARG2 >> /dev/null
	    echo "Done resetting power of DAQ $DAQ"
	else
	    echo "Could NOT located required scrip"
	fi
    elif [ $DAQ == 30 ]
    then
	PingIP 101
	if [ -f /home/daq/Diagnosis/power_reset_dirty.sh ]
	then
	    echo "Resetting the power of DAQ $DAQ ..."
	    echo "It might take about 20 sec. Please wait ... ..."
	    /home/daq/Diagnosis/power_reset_dirty.sh 0000 0001 >> /dev/null
	    echo "Done resetting the power of DAQ $DAQ"
	else
	    echo "Could NOT located required scrip"
	fi
    else
	echo "Invalid DAQ module"
    fi
}

ResetPower
